services:
  mysql:
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PW}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  dotnet:
    image: dotnet:latest
    build:
      context: .
      dockerfile: src/url/Dockerfile
    ports:
      - 8001:8001
    depends_on:
      - mysql
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8001
      ConnectionStrings__DefaultConnection: Server=mysql;Port=3306;Database=${DB_NAME};User=${DB_USER};Password=${DB_PW}

  next:
    image: next:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: frontend/next/Dockerfile
    ports:
      - 4000:4000
    volumes:
      - /var/lib/next/data
    restart: always

volumes:
  mysql-data: