services:
  mysql:
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PW}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 5432:3306
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
volumes:
  mysql-data: