apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet
spec:
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
      - name: dotnet
        image: dotnet:latest
        imagePullPolicy: Never
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ASPNETCORE_URLS
            value: "http://+:8001"
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: connection-secret
                key: connectionString
        envFrom:
          - secretRef:
              name: env-secrets
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-clusterip
spec:
  type: ClusterIP
  selector:
    app: dotnet
  ports:
  - port: 8001
    targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-lb
spec:
  type: LoadBalancer
  selector:
    app: dotnet
  ports:
  - port: 8001
    targetPort: 8001