apiVersion: v1
kind: Service
metadata:
  name: mysql-lb
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-lb
spec:
  type: LoadBalancer
  selector:
    app: dotnet
  ports:
  - port: 8001
    targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: next-lb
spec:
  type: LoadBalancer
  selector:
    app: next
  ports:
  - port: 4000
    targetPort: 4000